# Generated by Django 3.1.3 on 2020-11-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('temperature', models.FloatField(default=36.5)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='userID',
            field=models.IntegerField(default=0),
        ),
    ]
